services:
  dungeon-planner-db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dungeon-planner
    ports:
      - 5432:5432
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
volumes:
  pgdata: