# Generated by Django 5.2.4 on 2025-11-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('summary', models.CharField()),
                ('level_min', models.IntegerField()),
                ('level_max', models.IntegerField()),
                ('player_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('xp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('effect', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonPlanner.dungeon')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonPlanner.monster')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonPlanner.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='monsters',
            field=models.ManyToManyField(blank=True, through='dungeonPlanner.RoomMonster', to='dungeonPlanner.monster'),
        ),
        migrations.CreateModel(
            name='RoomTrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonPlanner.room')),
                ('trap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonPlanner.trap')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='traps',
            field=models.ManyToManyField(blank=True, through='dungeonPlanner.RoomTrap', to='dungeonPlanner.trap'),
        ),
        migrations.AddConstraint(
            model_name='roommonster',
            constraint=models.UniqueConstraint(fields=('room', 'monster'), name='unique_room_monster'),
        ),
    ]
