# Generated by Django 5.2.4 on 2025-07-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('summary', models.CharField()),
                ('level_min', models.IntegerField()),
                ('level_max', models.IntegerField()),
                ('player_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('xp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('effect', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonPlanner.dungeon')),
                ('monsters', models.ManyToManyField(blank=True, to='dungeonPlanner.monster')),
                ('traps', models.ManyToManyField(blank=True, to='dungeonPlanner.trap')),
            ],
        ),
    ]
