# Generated by Django 5.2.4 on 2026-03-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeonPlanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterMultiplierConfigRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.PositiveSmallIntegerField()),
                ('max', models.PositiveSmallIntegerField()),
                ('multiplier', models.FloatField()),
            ],
        ),
    ]
