# Generated by Django 5.2.4 on 2026-03-18 08:42

from django.db import migrations

multiplier_prepopulated_dicts = [
    { "min": 1, "max": 1, "multiplier": 0.5 },
    { "min": 2, "max": 2, "multiplier": 1 },
    { "min": 3, "max": 6, "multiplier": 1.5 },
    { "min": 7, "max": 10, "multiplier": 2 },
    { "min": 11, "max": 14, "multiplier": 3 }, 
    { "min": 15, "max": None, "multiplier": 4 }, 
]


def combine_names(apps, schema_editor):
    EncounterMultiplierConfigRow = apps.get_model("dungeonPlanner", "EncounterMultiplierConfigRow")
    for prepopulated_config in multiplier_prepopulated_dicts:
        EncounterMultiplierConfigRow.objects.create(
            min=prepopulated_config["min"],
            max=prepopulated_config["max"],
            multiplier=prepopulated_config["multiplier"],
        )

class Migration(migrations.Migration):

    dependencies = [
        ('dungeonPlanner', '0002_add_encounter_multiplier_config'),
    ]

    operations = [
        migrations.RunPython(combine_names)
    ]
