# Generated by Django 5.2.4 on 2026-03-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeonPlanner', '0003_prepopulate_encounter_multiplier_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterRatingConfigRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('easy', models.PositiveSmallIntegerField(null=True)),
                ('medium', models.PositiveSmallIntegerField(null=True)),
                ('hard', models.PositiveSmallIntegerField(null=True)),
                ('extreme', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
