# Generated by Django 5.2.4 on 2026-03-29 08:35

from django.db import migrations

rating_prepopulated_dicts = [
    {
      "level": 1,
      "easy": 50,
      "medium": 75,
      "hard": 100,
      "extreme": 125
    },
    {
      "level": 2,
      "easy": 100,
      "medium": 125,
      "hard": 200,
      "extreme": 250
    },
    {
      "level": 3,
      "easy": 200,
      "medium": 250,
      "hard": 400,
      "extreme": 500
    },
    {
      "level": 4,
      "easy": 400,
      "medium": 500,
      "hard": 800,
      "extreme": 1000
    },
]



def combine_names(apps, schema_editor):
    EncounterRatingConfigRow = apps.get_model("dungeonPlanner", "EncounterRatingConfigRow")
    for prepopulated_config in rating_prepopulated_dicts:
        EncounterRatingConfigRow.objects.create(
            level=prepopulated_config["level"],
            easy=prepopulated_config["easy"],
            medium=prepopulated_config["medium"],
            hard=prepopulated_config["hard"],
            extreme=prepopulated_config["extreme"],
        )

class Migration(migrations.Migration):

    dependencies = [
        ('dungeonPlanner', '0004_add_encounter_rating'),
    ]

    operations = [
        migrations.RunPython(combine_names)
    ]
