import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./tailwind-built.css";
import { NavBar } from "@/components/molecules/NavBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navBarLinks = [
  {
    title: "Monsters",
    url: "/monsters",
  },
  {
    title: "Traps",
    url: "/traps",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar links={navBarLinks}/>
        <>{children}</>
      </body>
    </html>
  );
}
