name: end-to-end

on:
  pull_request:
    branches:
      - main

jobs:
  server-db-unit-tests:
    runs-on: ubuntu-latest
    environment: dev

    env:
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} 
      DB_HOST: ${{ vars.DB_HOST }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USER: ${{ vars.DB_USER}}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create server .env file
        run: |
          cat > ./server/.env <<EOF
          DB_HOST=${{ vars.DB_HOST }}
          DB_NAME=${{ vars.DB_NAME }}
          DB_PORT=${{ vars.DB_PORT }}
          DB_USER=${{ vars.DB_USER}}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF

      - name: Create database .env file
        run: |
          cat > ./db/.env <<EOF
          POSTGRES_DB=${{ vars.POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker containers
        run: docker compose build dungeon-planner-db dungeon-planner-server

      - name: Var Check
        run: echo $POSTGRES_PASSWORD $DB_HOST

      - name: Start services
        run:  docker compose up -d dungeon-planner-db dungeon-planner-server

      - name: Run tests
        run: docker compose run --rm dungeon-planner-server python3 manage.py test

      - name: Shut down Docker Compose
        run: docker compose down